import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  ArrowLeft,
  Download,
  FileText,
  CheckCircle,
  DollarSign,
  Calculator,
  TrendingUp
} from 'lucide-react';

export default function EstimateResult() {
  const location = useLocation();
  const navigate = useNavigate();

  // Get data from navigation state, with fallbacks
  const {
    roomType,
    sqft,
    materialType,
    laborType,
    markup,
    totalEstimate,
    rooms,
    // estimateType,
    breakdown
  } = location.state || {};

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD'
    }).format(amount);
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();

    // Header with business branding
    doc.setFontSize(20);
    doc.setTextColor(0, 212, 255); // neon blue
    doc.text('AlphaQuote Professional Estimate', 14, 22);

    doc.setTextColor(0, 0, 0); // reset to black
    doc.setFontSize(12);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 35);
    doc.text(`Project: ${roomType}`, 14, 42);
    doc.text(`Total Size: ${sqft} sqft`, 14, 49);

    let currentY = 60;

    // If we have room breakdown, show it
    if (rooms && rooms.length > 0) {
      doc.setFontSize(14);
      doc.text('Room Breakdown:', 14, currentY);
      currentY += 10;

      const roomData = rooms.map(room => [
        room.name || 'Unnamed Room',
        `${room.sqft || 0} sqft`,
        room.material || 'Not specified',
        room.labor || 'Standard'
      ]);

      autoTable(doc, {
        startY: currentY,
        head: [['Room', 'Size', 'Material', 'Labor']],
        body: roomData,
        theme: 'grid',
        headStyles: { fillColor: [0, 212, 255] }
      });

      currentY = doc.lastAutoTable.finalY + 15;
    }

    // Cost breakdown
    const costData = [];
    if (breakdown) {
      costData.push(['Subtotal', `$${breakdown.subtotal?.toFixed(2) || '0.00'}`]);
      costData.push(['Markup', `${markup || 15}%`]);
      costData.push(['Markup Amount', `$${breakdown.markupAmount?.toFixed(2) || '0.00'}`]);
      costData.push(['Total Estimate', `$${breakdown.total?.toFixed(2) || totalEstimate?.toFixed(2) || '0.00'}`]);
    } else {
      costData.push(['Total Estimate', `$${totalEstimate?.toFixed(2) || '0.00'}`]);
    }

    autoTable(doc, {
      startY: currentY,
      head: [['Description', 'Amount']],
      body: costData,
      theme: 'grid',
      headStyles: { fillColor: [0, 212, 255] },
      footStyles: { fillColor: [0, 212, 255], textColor: [255, 255, 255] }
    });

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by AlphaQuote - Professional Estimation Software', 14, pageHeight - 20);
    doc.text('Contact: info@alphaquote.com | Visit: www.alphaquote.com', 14, pageHeight - 10);

    doc.save(`AlphaQuote_Estimate_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  // If no data is available, show a message
  if (!location.state) {
    return (
      <div className="min-h-screen bg-gray-900 text-white flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-neon-blue mb-4">No Estimate Data</h1>
          <p className="text-gray-300 mb-6">Please generate an estimate first.</p>
          <button
            onClick={() => navigate('/')}
            className="bg-neon-blue hover:bg-blue-500 text-white px-6 py-3 rounded-lg transition-all duration-300"
          >
            Start New Estimate
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 text-white font-body overflow-hidden relative">
      {/* Animated Background Elements */}
      <div className="absolute inset-0 overflow-hidden">
        {/* Blueprint Grid Pattern */}
        <div
          className="absolute inset-0 opacity-[0.02] animate-pulse"
          style={{
            backgroundImage: 'url("data:image/svg+xml,%3Csvg width=\'100\' height=\'100\' viewBox=\'0 0 100 100\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cdefs%3E%3Cpattern id=\'grid\' width=\'10\' height=\'10\' patternUnits=\'userSpaceOnUse\'%3E%3Cpath d=\'M 10 0 L 0 0 0 10\' fill=\'none\' stroke=\'%2314B8A6\' stroke-width=\'0.5\'/%3E%3C/pattern%3E%3C/defs%3E%3Crect width=\'100\' height=\'100\' fill=\'url(%23grid)\'/%3E%3C/svg%3E")'
          }}
        ></div>

        {/* Floating Particles */}
        <div className="absolute inset-0">
          {[...Array(12)].map((_, i) => (
            <motion.div
              key={i}
              className="absolute w-1 h-1 bg-primary/20 rounded-full"
              style={{
                left: `${Math.random() * 100}%`,
                top: `${Math.random() * 100}%`
              }}
              animate={{
                y: [0, -20, 0],
                opacity: [0.2, 0.8, 0.2]
              }}
              transition={{
                duration: 3 + Math.random() * 2,
                repeat: Infinity,
                delay: Math.random() * 2
              }}
            />
          ))}
        </div>
      </div>

      <div className="relative max-w-4xl mx-auto py-12 px-8">
        {/* Premium Header */}
        <motion.div
          className="text-center mb-12"
          initial={{ opacity: 0, y: -30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <motion.div
            className="inline-flex items-center justify-center w-20 h-20 bg-gradient-to-br from-primary/20 to-accent/20 rounded-full mb-6"
            animate={{ scale: [1, 1.1, 1] }}
            transition={{ duration: 2, repeat: Infinity }}
          >
            <CheckCircle className="w-10 h-10 text-primary" />
          </motion.div>
          <h1 className="text-5xl font-heading text-white mb-4">
            Estimate Complete
          </h1>
          <p className="text-xl text-slate-300">Your AlphaQuote estimate is ready</p>
        </motion.div>

        {/* Estimate Summary Card */}
        <motion.div
          className="bg-slate-900/50 backdrop-blur-sm rounded-2xl p-8 border border-slate-800/50 shadow-xl hover:shadow-2xl hover:shadow-primary/10 transition-all duration-300"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          whileHover={{ y: -4 }}
        >
          <div className="text-center mb-8">
            <div className="inline-flex items-center justify-center w-16 h-16 bg-primary/10 rounded-2xl mb-4">
              <FileText className="w-8 h-8 text-primary" />
            </div>
            <h2 className="text-3xl font-heading text-white">Estimate Summary</h2>
          </div>

          {/* Project Details */}
          <div className="space-y-6 mb-8">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-slate-800/50 rounded-xl p-6 border border-slate-700/50">
                <h3 className="text-sm font-medium text-gray-400 mb-1">Room Type</h3>
                <p className="text-lg font-semibold text-white">{roomType}</p>
              </div>

              <div className="bg-slate-800/50 rounded-xl p-6 border border-slate-700/50">
                <h3 className="text-sm font-medium text-slate-400 mb-2 flex items-center gap-2">
                  <TrendingUp className="w-4 h-4 text-primary" />
                  Square Footage
                </h3>
                <p className="text-lg font-semibold text-white">{sqft} sqft</p>
              </div>

              <div className="bg-slate-800/50 rounded-xl p-6 border border-slate-700/50">
                <h3 className="text-sm font-medium text-slate-400 mb-2 flex items-center gap-2">
                  <Calculator className="w-4 h-4 text-primary" />
                  Material Type
                </h3>
                <p className="text-lg font-semibold text-white">{materialType}</p>
              </div>

              <div className="bg-slate-800/50 rounded-xl p-6 border border-slate-700/50">
                <h3 className="text-sm font-medium text-slate-400 mb-2 flex items-center gap-2">
                  <Calculator className="w-4 h-4 text-accent" />
                  Labor Difficulty
                </h3>
                <p className="text-lg font-semibold text-white">{laborType}</p>
              </div>
            </div>

            <div className="bg-gray-700 rounded-lg p-4">
              <h3 className="text-sm font-medium text-gray-400 mb-1">Markup Percentage</h3>
              <p className="text-lg font-semibold text-white">{markup}%</p>
            </div>
          </div>

          {/* Total Estimate */}
          <div className="bg-gradient-to-r from-primary to-primary/80 rounded-2xl p-8 text-center mb-8 shadow-lg">
            <div className="flex items-center justify-center gap-3 mb-4">
              <DollarSign className="w-8 h-8 text-white" />
              <h3 className="text-xl font-heading text-white">Total Estimate</h3>
            </div>
            <p className="text-5xl font-bold text-white">{formatCurrency(totalEstimate)}</p>
          </div>

          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row gap-6">
            <motion.button
              onClick={handleDownloadPDF}
              className="group relative bg-gradient-to-r from-primary to-primary/80 text-white px-8 py-4 rounded-2xl text-lg font-semibold transition-all duration-300 flex items-center justify-center space-x-3 overflow-hidden flex-1"
              whileHover={{ scale: 1.05, y: -2 }}
              whileTap={{ scale: 0.98 }}
            >
              <div className="absolute inset-0 bg-gradient-to-r from-white/0 via-white/20 to-white/0 translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-700"></div>
              <Download className="w-6 h-6 relative z-10" />
              <span className="relative z-10">Download as PDF</span>
            </motion.button>

            <motion.button
              onClick={() => navigate('/')}
              className="group relative bg-gradient-to-r from-accent to-accent/80 text-white px-8 py-4 rounded-2xl text-lg font-semibold transition-all duration-300 flex items-center justify-center space-x-3 overflow-hidden flex-1"
              whileHover={{ scale: 1.05, y: -2 }}
              whileTap={{ scale: 0.98 }}
            >
              <div className="absolute inset-0 bg-gradient-to-r from-white/0 via-white/20 to-white/0 translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-700"></div>
              <ArrowLeft className="w-6 h-6 relative z-10" />
              <span className="relative z-10">Start New Estimate</span>
            </motion.button>
          </div>
        </motion.div>

        {/* Footer */}
        <motion.div
          className="text-center mt-12"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.4 }}
        >
          <p className="text-slate-400 text-sm">
            Thank you for using AlphaQuote! 🧮
          </p>
        </motion.div>
      </div>
    </div>
  );
}
